name: fvdb_build
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch::pytorch=2.4.0
  - pytorch::pytorch-cuda=12.1
  - git
  - gitpython
  - ca-certificates
  - certifi
  - openssl
  - cuda-toolkit=12.1
  - cuda-compiler=12.1
  - cuda-nvcc=12.1
  - cuda-cccl=12.1
  - cuda-libraries-static=12.1
  - gcc_linux-64=11
  - gxx_linux-64=11
  - setuptools>=68.2.2
  - cmake
  - make
  - ninja
  - sphinx>=7.0.0
  - sphinx_rtd_theme
  - myst-parser
  - linkify-it-py
  - numpy<2
  - tqdm
