name: fvdb_build
channels:
  - conda-forge
  - nodefaults
dependencies:
  - ca-certificates
  - certifi
  - cmake
  - cuda-command-line-tools
  - cuda-compiler
  - cuda-nvrtc-dev
  - cuda-nvtx-dev
  - cuda-version=12.0
  - cxx-compiler
  - gcc_linux-64=11
  - git
  - gitpython
  - gxx_linux-64=11
  - libcublas-dev
  - libcusolver-dev
  - libcusparse-dev
  - linkify-it-py
  - make
  - myst-parser
  - ninja
  - numpy<2
  - openssl
  - psutil
  - python=3.11
  - pytorch-gpu=2.4.1[build=cuda120*]
  - scikit-build-core
  - setuptools>=68.2.2
  - sphinx_rtd_theme
  - sphinx>=7.0.0
  - tqdm
  - zlib
