name: fvdb_build
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pytorch-gpu=2.4.1[build=cuda120*]
  - git
  - gitpython
  - ca-certificates
  - certifi
  - openssl
  - cuda-version=12.0
  - cuda-command-line-tools
  - cuda-compiler
  - libcusparse-dev
  - libcublas-dev
  - libcusolver-dev
  - gcc_linux-64=11
  - gxx_linux-64=11
  - cxx-compiler
  - setuptools>=68.2.2
  - cmake
  - make
  - ninja
  - sphinx>=7.0.0
  - sphinx_rtd_theme
  - myst-parser
  - linkify-it-py
  - numpy<2
  - tqdm
