name: fvdb
channels:
  - conda-forge
  - nodefaults
dependencies:
  - ca-certificates
  - certifi
  - clang-format=18
  - cmake
  - cuda-command-line-tools
  - cuda-compiler
  - cuda-nvrtc-dev
  - cuda-nvtx-dev
  - cuda-version=12.0
  - cxx-compiler
  - gcc_linux-64=11
  - git
  - gitpython
  - gxx_linux-64=11
  - ipython
  - jupyterlab
  - libcublas-dev
  - libcurand-dev
  - libcusolver-dev
  - libcusparse-dev
  - linkify-it-py
  - make
  - matplotlib
  - myst-parser
  - ninja
  - numpy<2
  - openssl
  - pandas
  - parameterized
  - pip
  - polyscope
  - psutil
  - pyrender
  - pytest-benchmark
  - python=3.11
  - pytorch-gpu=2.4.1[build=cuda120*]
  - rich
  - scikit-build-core
  - setuptools>=68.2.2
  - sparsehash
  - sphinx_rtd_theme
  - sphinx>=7.0.0
  - tensorboard
  - torchvision=0.19
  - tqdm
  - zlib
    ## 3dgs
  - fastai::opencv-python-headless
  - imageio
  - pillow
  - pyyaml
  - scikit-learn
  - torchmetrics
  - tyro
  - pip:
    - point-cloud-utils
    - https://nksr.s3.ap-northeast-1.amazonaws.com/dev-whls/pt24cu120/torchsparse-2.1.0-cp311-cp311-linux_x86_64.whl
    - https://nksr.s3.ap-northeast-1.amazonaws.com/dev-whls/pt24cu120/torchsparse_20-2.0.0b0-cp311-cp311-linux_x86_64.whl
    - https://nksr.s3.ap-northeast-1.amazonaws.com/dev-whls/pt24cu120/torch_scatter-2.1.2-cp311-cp311-linux_x86_64.whl
    ## 3dgs
    - viser
    ## 3dgs tests
    - oiio-static-python
