name: fvdb
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pytorch-gpu=2.4.1[build=cuda120*]
  - jupyterlab
  - torchvision=0.19
  - tensorboard
  - pip
  - git
  - gitpython
  - ca-certificates
  - certifi
  - openssl
  - cuda-version=12.0
  - cuda-command-line-tools
  - cuda-compiler
  - libcusparse-dev
  - libcublas-dev
  - libcusolver-dev
  - libcurand-dev
  - gcc_linux-64=11
  - gxx_linux-64=11
  - cxx-compiler
  - setuptools>=68.2.2
  - clang-format=18
  - cmake
  - make
  - ninja
  - sphinx>=7.0.0
  - sphinx_rtd_theme
  - myst-parser
  - linkify-it-py
  - numpy<2
  - tqdm
  - sparsehash
  - pandas
  - pytest-benchmark
  - polyscope
  - pyrender
  - rich
  - parameterized
  - ipython
  - matplotlib
    ## 3dgs
  - imageio
  - torchmetrics
  - fastai::opencv-python-headless
  - tyro
  - pillow
  - pyyaml
  - scikit-learn
  - pip:
    - point-cloud-utils
    - https://nksr.s3.ap-northeast-1.amazonaws.com/dev-whls/pt24cu120/torchsparse-2.1.0-cp311-cp311-linux_x86_64.whl
    - https://nksr.s3.ap-northeast-1.amazonaws.com/dev-whls/pt24cu120/torchsparse_20-2.0.0b0-cp311-cp311-linux_x86_64.whl
    - https://nksr.s3.ap-northeast-1.amazonaws.com/dev-whls/pt24cu120/torch_scatter-2.1.2-cp311-cp311-linux_x86_64.whl
    ## 3dgs
    - viser
    ## 3dgs tests
    - oiio-static-python
