name: fvdb_learn
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pytorch-gpu=2.4.1[build=cuda120*]
  - cuda-version=12.0
  - jupyterlab
  - torchvision
  - tensorboard
  - pip
  - git
  - gitpython
  - ca-certificates
  - certifi
  - openssl
  - parameterized
  - ipython
  - matplotlib
  - tqdm
  - sparsehash
  - pandas
  - pytest-benchmark
  - polyscope
  - numpy
  - pyrender
  - linkify-it-py
  ## 3dgs
  - imageio
  - torchmetrics
  - fastai::opencv-python-headless
  - tyro
  - pillow
  - pyyaml
  - scikit-learn
  - pip:
    - point-cloud-utils
    ## 3dgs
    - viser
    - https://nksr.s3.ap-northeast-1.amazonaws.com/dev-whls/pt24cu120/torch_scatter-2.1.2-cp311-cp311-linux_x86_64.whl
