name: fvdb_learn
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - jupyterlab
  - pytorch::pytorch=2.4.0
  - pytorch::pytorch-cuda=12.1
  - pytorch::pytorch-mutex=*=cuda
  - pytorch::torchvision
  - tensorboard
  - pip
  - git
  - gitpython
  - ca-certificates
  - certifi
  - openssl
  - parameterized
  - ipython
  - matplotlib
  - tqdm
  - sparsehash
  - pyg::pytorch-scatter=2.1.2
  - pandas
  - pytest-benchmark
  - polyscope
  - numpy<2
  - pyrender
  - linkify-it-py
  ## 3dgs
  - imageio
  - torchmetrics
  - py-opencv
  - tyro
  - pillow
  - pyyaml
  - scikit-learn
  - pip:
    - point-cloud-utils
    ## 3dgs
    - viser