name: fvdb_learn
channels:
  - pyg
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - pytorch-cuda=12.1
  - pytorch=2.4.0
  - tensorboard
  - pip
  - git
  - gitpython
  - ca-certificates
  - certifi
  - openssl
  - parameterized
  - ipython
  - matplotlib
  - tqdm
  - pyg
  - sparsehash
  - pyg::pytorch-scatter
  - pandas
  - pytest-benchmark
  - polyscope
  - numpy<2
  - pyrender
  - linkify-it-py
  - pip:
    - point-cloud-utils
    - python-pycg