# This release_base_environment is used by the 'Building Release Wheels' (.github/workflows/building.yml) GitHub Action
#   the cuda, python, and pytorch versions are configured and appended by the Action at runtime.
name: fvdb_release
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - git
  - gitpython
  - ca-certificates
  - certifi
  - openssl
  - gcc_linux-64=11
  - gxx_linux-64=11
  - cxx-compiler
  - setuptools>=68.2.2
  - cmake
  - make
  - ninja
  - sphinx>=7.0.0
  - sphinx_rtd_theme
  - myst-parser
  - linkify-it-py
  - numpy
  - tqdm
