name: fvdb_test
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pytorch-gpu=2.4.1[build=cuda120*]
  - tensorboard
  - cuda-version=12.0
  - pip>=23.3.1
  - git
  - gitpython
  - ca-certificates
  - certifi
  - openssl
  - parameterized
  - ipython
  - matplotlib
  - tqdm
  - sphinx>=7.0.0
  - sphinx_rtd_theme
  - myst-parser
  - pandas
  - rich
  - pytest-benchmark
  - numpy
  - linkify-it-py
  - polyscope
  - py-opencv=4.10[build=headless*]
  - imageio
  - scikit-learn
  - zlib
  - pip:
    - gsplat
    - pytest-markdown-docs
    - point-cloud-utils
    - https://nksr.s3.ap-northeast-1.amazonaws.com/dev-whls/pt24cu120/torchsparse-2.1.0-cp311-cp311-linux_x86_64.whl
    - https://nksr.s3.ap-northeast-1.amazonaws.com/dev-whls/pt24cu120/torchsparse_20-2.0.0b0-cp311-cp311-linux_x86_64.whl
    - https://nksr.s3.ap-northeast-1.amazonaws.com/dev-whls/pt24cu120/torch_scatter-2.1.2-cp311-cp311-linux_x86_64.whl
    ## 3dgs tests
    - oiio-static-python
