name: fvdb_test
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pytorch::pytorch=2.4.0
  - pytorch::pytorch-cuda=12.1
  - pytorch::pytorch-mutex=*=cuda
  - tensorboard
  - pip>=23.3.1
  - git
  - gitpython
  - ca-certificates
  - certifi
  - openssl
  - cuda-toolkit=12.1
  - cuda-compiler=12.1
  - cuda-nvcc=12.1
  - cuda-cccl=12.1
  - cuda-libraries-static=12.1
  - cuda-cudart-static=12.1
  - cuda-version=12.1
  - parameterized
  - gcc_linux-64=11
  - gxx_linux-64=11
  - cxx-compiler
  - setuptools>=68.2.2
  - cmake
  - make
  - ninja
  - ipython
  - matplotlib
  - tqdm
  - sparsehash
  - pyg::pytorch-scatter=2.1.2
  - sphinx>=7.0.0
  - sphinx_rtd_theme
  - myst-parser
  - pandas
  - rich
  - pytest-benchmark
  - numpy<2
  - py-openimageio
  - linkify-it-py
  - glm
  - polyscope
  - py-opencv
  - imageio
  - scikit-learn
  - pip:
    - gsplat
    - pytest-markdown-docs
    - point-cloud-utils
    - https://nksr.s3.ap-northeast-1.amazonaws.com/dev-whls/pt24cu121/torchsparse_20-2.0.0b0-cp310-cp310-linux_x86_64.whl
    - https://nksr.s3.ap-northeast-1.amazonaws.com/dev-whls/pt24cu121/torchsparse-2.1.0-cp310-cp310-linux_x86_64.whl
