#
# Try to find OPENEXRHALF library and include path.
# Once done this will define
#
# OPENEXRHALF_FOUND
# OPENEXRHALF_INCLUDE_PATH
# OPENEXRHALF_LIBRARY
# 

IF (WIN32)
	FIND_PATH( OPENEXRHALF_INCLUDE_PATH half.h
		$ENV{OPENEXRHALF_DIR}/Half
		DOC "The directory where Half.h resides")
	FIND_LIBRARY( OPENEXRHALF_LIBRARY
		NAMES Half
		PATHS
		$ENV{OPENEXRHALF_DIR}/vc/vc9/IlmBase/x64/Release
		DOC "The Half library")
ELSE (WIN32)
  # TODO
ENDIF (WIN32)

IF (OPENEXRHALF_INCLUDE_PATH)
	SET( OPENEXRHALF_FOUND 1 CACHE STRING "Set to 1 if OPENEXRHALF is found, 0 otherwise")
ELSE (OPENEXRHALF_INCLUDE_PATH)
	SET( OPENEXRHALF_FOUND 0 CACHE STRING "Set to 1 if OPENEXRHALF is found, 0 otherwise")
ENDIF (OPENEXRHALF_INCLUDE_PATH)

MARK_AS_ADVANCED( OPENEXRHALF_FOUND )
