
stages:
- stage: Build
  jobs:
  - job: testhou180
    displayName: Houdini 18.0
    pool:
      vmImage: 'ubuntu-16.04'
    container: aswf/ci-base:2019
    timeoutInMinutes: 0
    condition: variables['HOUPASS']
    steps:
    - bash: ci/install_houdini_azure.sh 18.0 ${HOUPASS}
    - bash: ci/build_houdini_azure.sh clang++ Release OFF
