
schedules:
- cron: "0 0 * * *"
  displayName: Daily build
  branches:
    include:
    - master
  always: true

stages:
- stage: Build
  jobs:
  - job: sonarcloud
    displayName: SonarCloud Static Analysis
    condition: in(variables['Build.Reason'], 'Manual', 'Schedule')
    pool:
      vmImage: 'ubuntu-16.04'
    container: aswftesting/ci-openvdb:2019
    timeoutInMinutes: 0
    steps:
    - bash: ci/build_sonar.sh
    - bash: ./build/openvdb/unittest/vdb_test -v
    - bash: ci/test_sonar.sh

  - job: testabi6
    displayName: and Test ABI=6
    pool:
      vmImage: 'ubuntu-16.04'
    container: aswftesting/ci-openvdb:2019
    timeoutInMinutes: 0
    steps:
    - bash: ci/build.sh clang++ Release 6 ON
    - bash: ./build/openvdb/unittest/vdb_test -v

  - job: testabi5
    displayName: and Test ABI=5
    pool:
      vmImage: 'ubuntu-16.04'
    container: aswftesting/ci-openvdb:2018
    timeoutInMinutes: 0
    steps:
    - bash: ci/build.sh clang++ Release 5 ON
    - bash: ./build/openvdb/unittest/vdb_test -v

  - job: testabi4
    displayName: and Test ABI=4
    pool:
      vmImage: 'ubuntu-16.04'
    container: aswftesting/ci-openvdb:2018
    timeoutInMinutes: 0
    steps:
    - bash: ci/build.sh clang++ Release 4 ON
    - bash: ./build/openvdb/unittest/vdb_test -v

  - job: testhou175
    displayName: Houdini 17.5
    pool:
      vmImage: 'ubuntu-16.04'
    container: aswftesting/ci-base:2018
    timeoutInMinutes: 0
    condition: variables['HOUPASS']
    steps:
    - bash: ci/install_houdini.sh 17.5 ${HOUPASS}
    - bash: ci/build_houdini.sh clang++ Release ON

  - job: testhou170
    displayName: Houdini 17.0
    pool:
      vmImage: 'ubuntu-16.04'
    container: aswftesting/ci-base:2018
    timeoutInMinutes: 0
    condition: variables['HOUPASS']
    steps:
    - bash: ci/install_houdini.sh 17.0 ${HOUPASS}
    - bash: ci/build_houdini.sh clang++ Release OFF

  - job: testhou165
    displayName: Houdini 16.5
    pool:
      vmImage: 'ubuntu-16.04'
    container: aswftesting/ci-base:2018
    timeoutInMinutes: 0
    condition: variables['HOUPASS']
    steps:
    - bash: ci/install_houdini.sh 16.5 ${HOUPASS}
    - bash: ci/build_houdini.sh clang++ Release OFF

  - job: testabi6noblosc
    displayName: and Test ABI=6 (No Blosc)
    pool:
      vmImage: 'ubuntu-16.04'
    container: aswftesting/ci-openvdb:2019
    timeoutInMinutes: 0
    steps:
    - bash: ci/build.sh clang++ Release 6 OFF
    - bash: ./build/openvdb/unittest/vdb_test -v

  - job: testhou175gcc
    displayName: Houdini 17.5 (GCC)
    pool:
      vmImage: 'ubuntu-16.04'
    container: aswftesting/ci-base:2018
    timeoutInMinutes: 0
    condition: variables['HOUPASS']
    steps:
    - bash: ci/install_houdini.sh 17.5 ${HOUPASS}
    - bash: ci/build_houdini.sh g++ Release OFF

  - job: testhou175debug
    displayName: Houdini 17.5 (Debug Mode)
    pool:
      vmImage: 'ubuntu-16.04'
    container: aswftesting/ci-base:2018
    timeoutInMinutes: 0
    condition: variables['HOUPASS']
    steps:
    - bash: ci/install_houdini.sh 17.5 ${HOUPASS}
    - bash: ci/build_houdini.sh clang++ Debug OFF

  - job: testabi6gcc
    displayName: ABI=6 (GCC)
    pool:
      vmImage: 'ubuntu-16.04'
    container: aswftesting/ci-openvdb:2019
    timeoutInMinutes: 0
    steps:
    - bash: ci/build.sh g++ Release 6 ON

  - job: testabi6debug
    displayName: ABI=6 (Debug)
    pool:
      vmImage: 'ubuntu-16.04'
    container: aswftesting/ci-openvdb:2019
    timeoutInMinutes: 0
    steps:
    - bash: ci/build.sh clang++ Debug 6 ON
