version: 0.2

env:
  variables:
    CXX: g++
    CC: gcc
  exported-variables:
    - CXX
    - CC

phases:
  install:
    commands:
      - dnf install -y tree

  pre_build:
    commands:
      # Verify the GPU and inspect CodeBuild's checked-out source
      - nvidia-smi
      - 'echo "CODEBUILD_SRC_DIR: $CODEBUILD_SRC_DIR"'
      - cd "$CODEBUILD_SRC_DIR"
      - tree

  build:
    commands:
      - echo "Add build commands here"
