get_filename_component(fullFolderName "${CMAKE_CURRENT_LIST_FILE}" DIRECTORY)
get_filename_component(folderName "${fullFolderName}" NAME)
string(REGEX REPLACE "([^-]*)-.*$" "\\1" PACKAGE_NAME ${folderName})
string(TOUPPER ${PACKAGE_NAME} UPPERCASE_PACKAGE_NAME)
string(REGEX REPLACE "[^-]*-(.*)$" "\\1" PACKAGE_VERSION ${folderName})

IF (CMAKE_CL_64)
	SET(ARCH "x64")
ELSE()
	SET(ARCH "x86")
endif()

if(MSVC)
	IF(MSVC90)
		SET(RUNTIME "msvc2008")
	ELSEIF(MSVC10)
		SET(RUNTIME "msvc2010")
	ELSEIF(MSVC11)
		SET(RUNTIME "msvc2012")
	ELSEIF(MSVC12)
		SET(RUNTIME "msvc2013")
	ENDIF(MSVC90)
else()
	SET(RUNTIME "unknown")
endif()

if("${PACKAGE_VERSION}" VERSION_LESS "${PACKAGE_FIND_VERSION}")
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
elseif(IS_DIRECTORY "${fullFolderName}/${RUNTIME}"  OR IS_DIRECTORY "${fullFolderName}/${RUNTIME}-${ARCH}"  OR IS_DIRECTORY "${fullFolderName}/${ARCH}")
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    if("${PACKAGE_FIND_VERSION}" STREQUAL "${PACKAGE_VERSION}")
        set(PACKAGE_VERSION_EXACT TRUE)
    endif()
else()
	
    set(PACKAGE_VERSION_UNSUITABLE TRUE)
endif()
