get_filename_component(fullFolderName "${CMAKE_CURRENT_LIST_FILE}" DIRECTORY)
get_filename_component(folderName "${fullFolderName}" NAME)
string(REGEX REPLACE "([^-]*)-.*$" "\\1" PACKAGE_NAME ${folderName})
string(TOUPPER ${PACKAGE_NAME} UPPERCASE_PACKAGE_NAME)
string(REGEX REPLACE "[^-]*-(.*)$" "\\1" PACKAGE_VERSION ${folderName})

if("${PACKAGE_VERSION}" VERSION_LESS "${PACKAGE_FIND_VERSION}")
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    if("${PACKAGE_FIND_VERSION}" STREQUAL "${PACKAGE_VERSION}")
        set(PACKAGE_VERSION_EXACT TRUE)
    endif()
endif()
