
# A pre-requisite of the GitHub Checks API is:
# Your project must be using CircleCI 2.0 with Workflows
# (https://circleci.com/docs/2.0/enable-checks/)

version: 2

jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: echo "hello world"
