name: fvdb_garfield
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pytorch-gpu=2.4.1[build=cuda120*]
  - cuda-version=12.0
  - cuda-command-line-tools
  - cuda-compiler
  - libcusparse-dev
  - libcublas-dev
  - libcusolver-dev
  - libcurand-dev
  - cuda-cudart-static
  - cuda-cudart
  - cuda-cudart-dev
  - gcc_linux-64=11
  - gxx_linux-64=11
  - cxx-compiler
  - pip
  - git
  - gitpython
  - ipython
  - tqdm
  - numpy<2
  - tyro
  - gdown
  ##  nerfstudio
  - tensorboard
  - torchvision
  - open3d>=0.16.0
  - transformers
  - trimesh
  - ninja
  - fastai::opencv-python-headless
  - imageio
  - torchmetrics
  - protobuf
  ##  garfield
  - scikit-learn
  - rapidsai::cuml
  - rapidsai::libcumlprims
  - pip:
    ##  nerfstudio
    # NOTE: have had to build tiny-cuda-nn and nerfacc from source for CUDA 12
    - https://nksr.s3.ap-northeast-1.amazonaws.com/dev-whls/pt24cu120/nerfacc-0.5.2-cp311-cp311-linux_x86_64.whl
    - https://nksr.s3.ap-northeast-1.amazonaws.com/dev-whls/pt24cu120/tinycudann-1.7-cp311-cp311-linux_x86_64.whl
    - gsplat
    - viser
    - nerfstudio>=1.0.0
    ##  garfield
    - torchtyping
