
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:11 (project)"
    message: |
      The system is: Linux - 6.11.0-17-generic - x86_64
...
