FROM oddsocks/nanovdb:dev-base

ENV ROOT_PATH /repo

WORKDIR $ROOT_PATH/

COPY __dist/repo.tar $ROOT_PATH/

RUN \
    tar -xvf $ROOT_PATH/repo.tar && \
	dos2unix $ROOT_PATH/ci/*.sh && \
	chmod +x $ROOT_PATH/ci/*.sh
