FROM oddsocks/nanovdb:dev-base

ENV ROOT_PATH /repo

WORKDIR $ROOT_PATH/

COPY __dist/repo.tar $ROOT_PATH/

RUN \
    tar -xvf $ROOT_PATH/repo.tar && \
	dos2unix $ROOT_PATH/ci/*.sh && \
	chmod +x $ROOT_PATH/ci/*.sh

RUN \
    ./ci/build_core.sh clang++ clang Release \
        -DNANOVDB_USE_OPTIX=OFF \
        -DNANOVDB_USE_CUDA=OFF

# current status:
#
# NANOVDB_BUILD_UNITTESTS must be false because gtest fails to compile inside wine with:
#    0080:err:msvcrt:get_calling_convention Unknown calling convention V
#    0081:err:msvcrt:get_calling_convention Unknown calling convention @
#    ...
#
# examples fails to run due to missing WINE implementation of fma.

RUN \
    wine --version && \
    wine wineboot && \
    ./ci/build_core_toolchain.sh $ROOT_PATH/ci/wine-toolchain.cmake msvc16 Release \
        -DNANOVDB_USE_OPENVDB=OFF \
        -DNANOVDB_USE_TBB=OFF \
        -DNANOVDB_USE_ZLIB=OFF \
        -DNANOVDB_USE_BLOSC=OFF \
        -DNANOVDB_BUILD_TOOLS=ON \
        -DNANOVDB_BUILD_UNITTESTS=OFF

RUN \
    ./ci/build_docs.sh

RUN \
    ./ci/test_core.sh clang && \
    ./ci/test_render.sh clang
