#ifndef OPENVDBLINK_EXPLICITGRIDS_OPENVDBVEC2IGRID_HAS_BEEN_INCLUDED
#define OPENVDBLINK_EXPLICITGRIDS_OPENVDBVEC2IGRID_HAS_BEEN_INCLUDED

#include <openvdb/openvdb.h>

#include "../OpenVDBGrid.h"

using OpenVDBVec2IGrid = OpenVDBGrid<Vec2i>;

#endif // OPENVDBLINK_EXPLICITGRIDS_OPENVDBVEC2IGRID_HAS_BEEN_INCLUDED
