#ifndef OPENVDBLINK_EXPLICITGRIDS_OPENVDBVEC3IGRID_HAS_BEEN_INCLUDED
#define OPENVDBLINK_EXPLICITGRIDS_OPENVDBVEC3IGRID_HAS_BEEN_INCLUDED

#include <openvdb/openvdb.h>

#include "../OpenVDBGrid.h"

using OpenVDBVec3IGrid = OpenVDBGrid<Vec3i>;

#endif // OPENVDBLINK_EXPLICITGRIDS_OPENVDBVEC3IGRID_HAS_BEEN_INCLUDED
