#ifndef OPENVDBLINK_EXPLICITGRIDS_OPENVDBVEC3DGRID_HAS_BEEN_INCLUDED
#define OPENVDBLINK_EXPLICITGRIDS_OPENVDBVEC3DGRID_HAS_BEEN_INCLUDED

#include <openvdb/openvdb.h>

#include "../OpenVDBGrid.h"

using OpenVDBVec3DGrid = OpenVDBGrid<Vec3d>;

#endif // OPENVDBLINK_EXPLICITGRIDS_OPENVDBVEC3DGRID_HAS_BEEN_INCLUDED
