#ifndef OPENVDBLINK_EXPLICITGRIDS_OPENVDBVEC2SGRID_HAS_BEEN_INCLUDED
#define OPENVDBLINK_EXPLICITGRIDS_OPENVDBVEC2SGRID_HAS_BEEN_INCLUDED

#include <openvdb/openvdb.h>

#include "../OpenVDBGrid.h"

using OpenVDBVec2SGrid = OpenVDBGrid<Vec2s>;

#endif // OPENVDBLINK_EXPLICITGRIDS_OPENVDBVEC2SGRID_HAS_BEEN_INCLUDED
