#ifndef OPENVDBLINK_EXPLICITGRIDS_OPENVDBVEC2DGRID_HAS_BEEN_INCLUDED
#define OPENVDBLINK_EXPLICITGRIDS_OPENVDBVEC2DGRID_HAS_BEEN_INCLUDED

#include <openvdb/openvdb.h>

#include "../OpenVDBGrid.h"

using OpenVDBVec2DGrid = OpenVDBGrid<Vec2d>;

#endif // OPENVDBLINK_EXPLICITGRIDS_OPENVDBVEC2DGRID_HAS_BEEN_INCLUDED
