name: fvdb_maskpls
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pytorch-gpu=2.4.1[build=cuda120*]
  - pip
  - git
  - gitpython
  - ipython
  - tqdm
  - numpy<2
  - tyro
  - scikit-learn
  - py-opencv
  - imageio
  - pip:
    - pye57
