name: fvdb_maskpls
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pytorch::pytorch=2.4.0
  - pytorch::pytorch-cuda=12.1
  - pytorch::pytorch-mutex=*=cuda
  - pip
  - git
  - gitpython
  - ipython
  - tqdm
  - numpy<2
  - tyro
  - scikit-learn
  - py-opencv
  - imageio
  - pip:
    - pye57