
SET ( MANIFEST "${CMAKE_CURRENT_BINARY_DIR}/install_manifest.txt" )

IF ( NOT EXISTS ${MANIFEST} )
  MESSAGE ( FATAL_ERROR "Cannot find install manifest: '${MANIFEST}'" )
ENDIF ()

FILE (STRINGS ${MANIFEST} INSTALLED_FILES )
FOREACH ( INSTALLED_FILE ${INSTALLED_FILES} )
  IF ( EXISTS ${INSTALLED_FILE} )
    MESSAGE ( STATUS "Uninstalling: ${INSTALLED_FILE}")
    EXEC_PROGRAM (
       ${CMAKE_COMMAND} ARGS "-E remove ${INSTALLED_FILE}"
       OUTPUT_VARIABLE stdout
       RETURN_VALUE RESULT
    )

    IF ( NOT "${RESULT}" STREQUAL 0 )
      MESSAGE ( FATAL_ERROR "Failed to remove file: '${INSTALLED_FILE}'." )
    ENDIF ()
  ENDIF ()
ENDFOREACH (INSTALLED_FILE)
