name: fVDB Code Style
on:
  pull_request:
    branches:
        - 'master'
        - 'feature/**'
        - 'pr/**'
    paths-ignore:
        - 'CHANGES'
        - 'CODEOWNERS'
        - 'doc/**'
        - 'ci/**'
        - 'openvdb/**'
        - 'openvdb_cmd/**'
        - 'openvdb_ax/**'
        - 'openvdb_maya/**'
        - 'openvdb_houdini/**'
        - 'openvdb_wolfram/**'
        - 'tsc/**'
        - 'nanovdb/**'
        - 'pendingchanges/**'
        - '**.md'
        - 'fvdb/docs/**'
        - 'fvdb/env/**'
        - 'fvdb/notebooks/**'



# Allow subsequent pushes to the same PR or REF to cancel any previous jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-python-black-lint:
    name: Check Python code style with black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --verbose --target-version=py311 --line-length=120"
          src: "."
          version: "~= 24.0"

  test-cpp-clang-format-lint:
    name: Check C++ code style with clang-format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.18.2
      with:
        source: 'src/'
        extensions: 'h,cpp,cc,cu,ch'
        clangFormatVersion: 18
        style: file

  include-guards:
    name: Check include guards
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: swahtz/include-guards-check-action@master
      with:
        path: 'src/'
        pattern: 'FVDB_{path}'

  check-spdx-identifiers:
    name: Check SPDX identifiers
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: enarx/spdx@master
      with:
        licenses: |-
          Apache-2.0