
name: GPU

on:
  push:
    branches-ignore:
      - RB-0.*
      - RB-1.*
      - gh-pages
  pull_request:
    branches:
        - '**'

jobs:
  # ---------------------------------------------------------------------------
  # Linux GPU (AWS CodeBuild)
  # ---------------------------------------------------------------------------

  linux_gpu:
    name: 'Linux CentOS 7 VFX CY2020 GPU <GCC 6.3.1>'
    # Don't run on OCIO forks
    # GH-hosted VM. The build runs in CentOS 7 'container' hard-coded in 
    # AWS CodeBuild project.
    # TODO: Add support for dynamic GH Action defined CodeBuild 
    #       container choice.
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.CODEBUILD_ID }}
          aws-secret-access-key: ${{ secrets.CODEBUILD_SECRET }}
          aws-region: us-west-2
      - name: Validate AWS Credentials
        run: |
            aws sts get-caller-identity