name: Release Python Bindings to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      test_pypi:
        type: boolean
        description: 'Test release: publish on test.pypi.org'
        default: false

  publish:
    name: Publish Python packages on PyPI
    needs: [build-sdist, build-wheels]
    runs-on: ubuntu-latest
    steps:
      - name:   Download artifacts from commit ${{ github.sha }}
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: wheels.yml
          workflow_conclustion: success
          commit: ${{ github.sha }}
          name: dist
          path: dist

      - name: 🧪 Publish to PyPI Testing
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ inputs.test_pypi }}
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: dist

      - name: 🎉 Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ !inputs.test_pypi }}
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: dist
